# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.



  config.vm.define "availability-1" do |node|
    node.vm.box = "ubuntu/trusty64"
    node.vm.network "public_network"
    node.vm.synced_folder "./data/availability-1", "/data"
    node.vm.synced_folder "./data/bin", "/data/bin"
    node.vm.provision "shell", inline: " sudo apt-get install dnsmasq -y;echo 'server=/consul/127.0.0.1#8600' > /etc/dnsmasq.d/consul; sudo service dnsmasq restart;"      
    node.vm.network :forwarded_port, guest: 22, host: 3215, bridge: "en0: Wi-Fi (AirPort)"
  end

  config.vm.define "availability-2" do |node|
    node.vm.box = "ubuntu/trusty64"
    node.vm.network "public_network"
    node.vm.synced_folder "./data/availability-2", "/data"
    node.vm.synced_folder "./data/bin", "/data/bin"
    node.vm.provision "shell", inline: " sudo apt-get install dnsmasq -y;echo 'server=/consul/127.0.0.1#8600' > /etc/dnsmasq.d/consul; sudo service dnsmasq restart;"      
    node.vm.network :forwarded_port, guest: 22, host: 3205, bridge: "en0: Wi-Fi (AirPort)"
  end
 
  config.vm.define "payment" do |node|
    node.vm.box = "ubuntu/trusty64"
    node.vm.network "public_network"
    node.vm.synced_folder "./data/payment", "/data"
    node.vm.synced_folder "./data/bin", "/data/bin"
    node.vm.provision "shell", inline: " sudo apt-get install dnsmasq -y;echo 'server=/consul/127.0.0.1#8600' > /etc/dnsmasq.d/consul; sudo service dnsmasq restart;"
    node.vm.network :forwarded_port, guest: 22, host: 3210, bridge: "en0: Wi-Fi (AirPort)"
  end
 
  config.vm.define "db" do |node|
    node.vm.box = "ubuntu/trusty64"
    node.vm.network "public_network"
    node.vm.synced_folder "./data/db", "/data"
    node.vm.synced_folder "./data/bin", "/data/bin"
    node.vm.provision "shell", inline: " sudo apt-get install dnsmasq -y;echo 'server=/consul/127.0.0.1#8600' > /etc/dnsmasq.d/consul; sudo service dnsmasq restart;"      
    node.vm.network :forwarded_port, guest: 22, host: 3250, bridge: "en0: Wi-Fi (AirPort)"
  end
end
